# Generated by Django 6.0.1 on 2026-01-24 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('cuidador', 'Cuidador(a)'), ('enfermeiro', 'Enfermeiro(a)')], max_length=20)),
                ('conselho', models.CharField(choices=[('CRBM', 'CRBM - Biomedicina'), ('CRM', 'CRM - Medicina'), ('COREN', 'COREN - Enfermagem'), ('CRO', 'CRO - Odontologia'), ('CRF', 'CRF - Farmácia'), ('CRP', 'CRP - Psicologia'), ('CREFITO', 'CREFITO - Fisioterapia / Terapia Ocupacional'), ('CRBio', 'CRBio - Biologia'), ('CREFONO', 'CREFONO - Fonoaudiologia'), ('CRN', 'CRN - Nutrição'), ('CRESS', 'CRESS - Serviço Social'), ('CREF', 'CREF - Educação Física'), ('CRQ', 'CRQ - Química'), ('OUTRO', 'Outro / Não se aplica')], max_length=40)),
                ('numero_conselho', models.CharField(max_length=30)),
                ('ContextoAtuacao', models.CharField(default='DOM', editable=False, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
