# Generated by Django 6.0.1 on 2026-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
