# Generated by Django 6.0.1 on 2026-01-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_profissional_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='onboarding_concluido',
            field=models.BooleanField(default=False),
        ),
    ]
