# Generated by Django 6.0.1 on 2026-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.DateField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('diagnostico_principal', models.TextField()),
                ('familiar_responsavel', models.CharField(max_length=200)),
                ('contato_familiar', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
