# Generated by Django 6.0.1 on 2026-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=100),
        ),
    ]
