# Generated by Django 6.0.1 on 2026-01-27 10:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contato_familiar',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
